name: f_dart_streams
description: dart streams
version: 1.0.0
homepage: homepage: https://github.com/celycodes/jornada_dart 

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
