name: e_dart_consumo_api
description: Jornada Dart consumo de api
version: 1.0.0
homepage: https://github.com/celycodes

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
